myblog/config/routes.rb
Rails.application.routes.draw do
  resources :publishing_terms
  resources :unit_prices
  resources :contact_histories
  resources :notification2s
  resources :notifications
  resources :publishing_fees
  resources :client_unit_prices
  resources :client_publishing_settings
  devise_for :users
  get 'welcome/index'
  resources :categories
  resources :shops
  resources :diaries
  resources :articles
  resources :clients


  # namespace :api, {format: 'json'} do
  #   namespace :v1 do
  #     resources :articles, only: [:index, :show, :create]
  #     resources :clients, only: [:index, :show, :create]
  #     resources :product, only: [:index, :show]
  #   end
  # end

  root "welcome#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

myblog/app/models/diary.rb
class Diary < ApplicationRecord
end

myblog/app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: [:show, :edit, :update, :destroy]

  # GET /diaries
  # GET /diaries.json
  def index
    @diaries = Diary.all
  end

  # GET /diaries/1
  # GET /diaries/1.json
  def show
  end

  # GET /diaries/new
  def new
    @diary = Diary.new
  end

  # GET /diaries/1/edit
  def edit
  end

  # POST /diaries
  # POST /diaries.json
  def create
    @diary = Diary.new(diary_params)

    respond_to do |format|
      if @diary.save
        format.html { redirect_to @diary, notice: 'Diary was successfully created.' }
        format.json { render :show, status: :created, location: @diary }
      else
        format.html { render :new }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diaries/1
  # PATCH/PUT /diaries/1.json
  def update
    respond_to do |format|
      if @diary.update(diary_params)
        format.html { redirect_to @diary, notice: 'Diary was successfully updated.' }
        format.json { render :show, status: :ok, location: @diary }
      else
        format.html { render :edit }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diaries/1
  # DELETE /diaries/1.json
  def destroy
    @diary.destroy
    respond_to do |format|
      format.html { redirect_to diaries_url, notice: 'Diary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diary
      @diary = Diary.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def diary_params
      params.require(:diary).permit(:content)
    end
end

myblog/app/helpers/diaries_helper.rb
module DiariesHelper
end

myblog/app/views/diaries/_form.html.erb
<%= form_with(model: diary, local: true) do |form| %>
  <% if diary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(diary.errors.count, "error") %> prohibited this diary from being saved:</h2>

      <ul>
        <% diary.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

myblog/app/views/diaries/edit.html.erb
<h1>Editing Diary</h1>

<%= render 'form', diary: @diary %>

<%= link_to 'Show', @diary %> |
<%= link_to 'Back', diaries_path %>

myblog/app/views/diaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Diaries</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @diaries.each do |diary| %>
      <tr>
        <td><%= diary.content %></td>
        <td><%= link_to 'Show', diary %></td>
        <td><%= link_to 'Edit', edit_diary_path(diary) %></td>
        <td><%= link_to 'Destroy', diary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Diary', new_diary_path %>
<%= link_to 'Shops', shops_path %>

myblog/app/views/diaries/new.html.erb
<h1>New Diary</h1>

<%= render 'form', diary: @diary %>

<%= link_to 'Back', diaries_path %>

myblog/app/views/diaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @diary.content %>
</p>

<%= link_to 'Edit', edit_diary_path(@diary) %> |
<%= link_to 'Back', diaries_path %>