myblog/config/routes.rb
Rails.application.routes.draw do
  resources :publishing_terms
  resources :unit_prices
  resources :contact_histories
  resources :notification2s
  resources :notifications
  resources :publishing_fees
  resources :client_unit_prices
  resources :client_publishing_settings
  devise_for :users
  get 'welcome/index'
  resources :categories
  resources :shops
  resources :diaries
  resources :articles
  resources :clients


  # namespace :api, {format: 'json'} do
  #   namespace :v1 do
  #     resources :articles, only: [:index, :show, :create]
  #     resources :clients, only: [:index, :show, :create]
  #     resources :product, only: [:index, :show]
  #   end
  # end

  root "welcome#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

myblog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

myblog/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
end

myblog/app/models/category.rb
class Category < ApplicationRecord
  has_many :shops
end

myblog/app/models/client.rb
class Client < ApplicationRecord
  has_one :client_publishing_setting, foreign_key: 'client_id'
  has_one :client_unit_price, foreign_key: 'client_id'
end

myblog/app/models/client_unit_price.rb
class ClientUnitPrice < ApplicationRecord
end

myblog/app/models/diary.rb
class Diary < ApplicationRecord
end

myblog/app/models/notification2.rb
class Notification2 < ApplicationRecord
end

myblog/app/models/publishing_fee.rb
class PublishingFee < ApplicationRecord
end

myblog/app/models/publishing_term.rb
class PublishingTerm < ApplicationRecord
  belongs_to :client_publishing_setting
end

myblog/app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :category
end

myblog/app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

myblog/app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    if params[:name_key]
      @shops = Shop.where('name LIKE ?', "%#{params[:name_key]}%")
    else
      @shops = Shop.all
    end
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shop_params
      params.require(:shop).permit(:category_id, :name, :address)
    end
end

myblog/app/helpers/application_helper.rb
module ApplicationHelper
end

myblog/app/helpers/articles_helper.rb
module ArticlesHelper
end

myblog/app/helpers/categories_helper.rb
module CategoriesHelper
end

myblog/app/helpers/clients_helper.rb
module ClientsHelper
end

myblog/app/helpers/diaries_helper.rb
module DiariesHelper
end

myblog/app/helpers/notification2s_helper.rb
module Notification2sHelper
end

myblog/app/helpers/shops_helper.rb
module ShopsHelper
end

myblog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

myblog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <p><%= t('hello') %></p>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <!-- Fixed navbar -->
  <nav class='navbar navbar-inverse navbar-fixed-top'>
    <div class='container'>
      <div class='navbar-header'>
        <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#navbar' aria-expanded='false' aria-controls='navbar'>
          <span class='sr-only'>Toggle navigation</span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
        </button>
        <%= link_to 'My Blog', root_path, class: 'navbar-brand' %>
      </div>
      <div id='navbar' class='collapse navbar-collapse'>
        <ul class='nav navbar-nav'>
          <li><%= link_to 'Shop', shops_path %></li>
          <li><%= link_to 'Category', categories_path %></li>
          <li><%= link_to 'Diary', diaries_path %></li>
          <li><%= link_to 'Articly', articles_path %></li>
          <li><%= link_to 'Notification', notification2s_path %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>


  </nav>

  <div class="sidebar">
    <div class="sidebar-wrapper">
      <div class="sidebar-link-area">
        <!-- サイドバーメニュー -->
        <p><%= link_to 'Shop', shops_path %></p>
        <p><%= link_to 'Category', categories_path %></p>
        <p><%= link_to 'Diary', diaries_path %></p>
        <p><%= link_to 'Articly', articles_path %></p>
        <p><%= link_to 'Notification', notification2s_path %></p>
      </div>
    </div>
  </div>

  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.name %></strong>.
    <%= link_to "Settings", edit_user_registration_path %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
  <% end %>

  <div class='container'>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
  </body>

  <style>
    .side {
      position: absolute;
      width: 146px;
      height: 83px;
      left: 0px;
      top: 0px;

      font-family: Roboto;
      font-style: normal;
      font-weight: normal;
      font-size: 24px;
      line-height: 28px;
      display: flex;
      align-items: center;
      text-align: center;

      color: #000000;
    }
    .sidebar {
      background-color: #191970;
      height: 100%; /* サイドバーの高さ */
      width: 200px; /* サイドバーのwidthを指定 */
      max-width: 200px; /* widthの最大値 */
      opacity: 0.9.5; /* 透過する 0に近くほど透過する */
      position: fixed; /* 左上に要素を固定する(スクロールしても位置は固定される) */
      overflow-x: hidden; /* 横軸ではみ出た要素を非表示にする */
      box-sizing: border-box; /* paddingとborderを、widthとheightに含める */
      padding-left: 40px; /* サイドバー内のリンクの位置を右にずらす */
    }

    .sidebar-link-area {
      padding-top: 20px; /* サイドバーリンクの上部に空白を作る */
    }

    .sidebar-link {
      color: #ffffff; /* リンクの文字色を白に */
    }

    .sidebar-link:hover {
      color: #ffffff /* マウスがリンクに乗った時も文字色を白に */
    }

    .container {
      /* display: flex; 要素を横並びにする */
      /*flex-direction: column; !* 要素の並び順の主軸を指定 上 => 下 *!*/
      /*min-height: 100vh; !* 要素の高さの最小値を指定 vhはviewport(表示領域) heightの略 *!*/

      /* サイドバーのwidth分だけ範囲を削除 */
      width: calc(100% - 200px);

      /* サイドバーで隠れるので右に寄せる */
      margin: 0 0 0 202px;
    }

  </style>
</html>