myblog/config/routes.rb
Rails.application.routes.draw do
  resources :publishing_terms
  resources :unit_prices
  resources :contact_histories
  resources :notification2s
  resources :notifications
  resources :publishing_fees
  resources :client_unit_prices
  resources :client_publishing_settings
  devise_for :users
  get 'welcome/index'
  resources :categories
  resources :shops
  resources :diaries
  resources :articles
  resources :clients


  # namespace :api, {format: 'json'} do
  #   namespace :v1 do
  #     resources :articles, only: [:index, :show, :create]
  #     resources :clients, only: [:index, :show, :create]
  #     resources :product, only: [:index, :show]
  #   end
  # end

  root "welcome#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

myblog/app/models/client.rb
class Client < ApplicationRecord
  has_one :client_publishing_setting, foreign_key: 'client_id'
  has_one :client_unit_price, foreign_key: 'client_id'
end

myblog/app/controllers/api/v1/clients_controller.rb
class Api::V1::ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index

    @clients = Client.all
    # ClientPublishingSetting.all
    # ClientPublishingSetting.joins(:client_id)

    # Client.joins(:client_publishing_setting)
    # client_publishing_setting
    # posts_needed = Client.joins(:client)
    #                    .select("
    #   posts.id,
    #   posts.name,
    #   description, #ここはusersテーブルと名前が被らない
    #   user_id, #ここはusersテーブルと名前が被らない
    #   users.name AS user_name #別名を付けられる
    #   ")
    # render json: posts_needed

    # @clients = Client.joins(:client_publishing_setting)

    # @clients = Client.all
    # @clients_publish = ClientPublishingSetting.all
    # @clients = Client.where(client_id: @clients_publish)


    # @c = Client.all
    # @clients = ClientPublishingSetting.where(client_id: @c.client_id)


    # @clients = Client.all
    render json: @clients
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    Client.joins(:client_publishing_setting).select("clients.id", "client_publishing_settings.comment AS c_name").limit(1)
    render json: @client
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:id, :client_id, :name, :admin_comment, :area_important, :nav_id)
    end


    def client_needed
      client_needed = Client.joins(:client_publishing_setting).select("clients.*,client_publishing_settings.name AS c_name")
      render json: client_needed
    end
end

myblog/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    # @clients = Client.all
    # @clients = ClientPublishingSetting.order(:client_id).all

    # @clientPublishingSettings = ClientPublishingSetting.order(:client_id).all
    @clients = PublishingTerm.all
    # @clients = PublishingTerm.order(:client_id).all


  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])

      @client_publish_setting = ClientPublishingSetting.find(params[:id])
      # @client_publish_setting = ClientPublishingSetting.find(params[:id])


      # @publishing_term = PublishingTerm.all
      # @publishing_term = PublishingTerm.where(ids: client_publish.id)
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:id, :client_id, :name, :admin_comment, :area_important, :nav_id)
    end
end

myblog/app/helpers/clients_helper.rb
module ClientsHelper
end

myblog/app/views/clients/_basic_info.html.erb
<div>基本情報</div>
<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Id:</strong>
  <%= @client.id %>
</p>

myblog/app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.text_field :id %>
  </div>

  <div class="field">
    <%= form.label :client_id %>
    <%= form.text_field :client_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :admin_comment %>
    <%= form.text_field :admin_comment %>
  </div>

  <div class="field">
    <%= form.label :area_important %>
    <%= form.text_field :area_important %>
  </div>

  <div class="field">
    <%= form.label :nav_id %>
    <%= form.number_field :nav_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

myblog/app/views/clients/_publishing_setting.html.erb
<p>publishing_term</p>


<div>掲載設定</div>
<!--<p>-->
<!--  <strong>Name:</strong>-->
  <%#= @publishing_term %>
<!--</p>-->

<p>
  <strong>Id:</strong>
  <% if @publishing_setting.blank? %>

  <% else %>
    <%= @publishing_setting.comment %>
  <% end %>
</p>

myblog/app/views/clients/_publishing_term.html.erb
<p>publishing_term</p>


<div>掲載設定</div>
<!--<p>-->
<!--  <strong>Name:</strong>-->
  <%#= @publishing_term %>
<!--</p>-->

<p>
  <strong>Id:</strong>
  <%= @publishing_term.id %>
</p>

myblog/app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

myblog/app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th style="width: 100px;">クライアント名</th>
      <th style="width: 100px;">ID</th>
      <th style="width: 300px;">掲載</th>
      <th style="width: 500px;">開始タイマー</th>
      <th style="width: 500px;">停止タイマー</th>
      <th style="width: 500px;">当月予算上限</th>
      <th style="width: 500px;">備考</th>
      <th style="width: 500px;">最終編集</th>
      <th colspan="3">操作</th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <% if client.client_publishing_setting.client.blank? %>
          <td style="width: 500px;">クライアント名</td>
        <% else %>
          <td style="width: 500px;"><%= client.client_publishing_setting.client.name %></td>
        <% end %>

        <% if client.client_publishing_setting.client.blank? %>
          <td style="width: 500px;">ID</td>
        <% else %>
          <td style="width: 100px;"><%= client.client_publishing_setting.client.id %></td>
        <% end %>

        <% if client.client_publishing_setting.client.blank? %>
          <td style="width: 500px;">掲載</td>
        <% else %>
          <td style="width: 100px;"></td>
        <% end %>

        <% if client.client_publishing_setting.client.blank? %>
          <td style="width: 500px;">開始タイマー</td>
        <% else %>
          <td style="width: 100px;"><%= client.begin_at %></td>
        <% end %>

        <% if client.client_publishing_setting.client.blank? %>
          <td style="width: 500px;">停止タイマー</td>
        <% else %>
          <td style="width: 100px;"><%= client.end_at %></td>
        <% end %>

        <% if client.client_publishing_setting.client.blank? %>
          <td style="width: 500px;">当月予算上限</td>
        <% else %>
          <td style="width: 100px;"></td>
        <% end %>

        <% if client.client_publishing_setting.client.blank? %>
          <td style="width: 500px;"></td>
        <% else %>
          <td style="width: 300px;"><%= client.client_publishing_setting.client.admin_comment %></td>
        <% end %>

        <% if client.client_publishing_setting.client.blank? %>
          <td style="width: 500px;">最終編集</td>
        <% else %>
          <td style="width: 100px;"><%= client.client_publishing_setting.client.updated_at %></td>
        <% end %>



        <!--        <td><%#= client.client_publishing_settings.comment %></td>-->
<!--        <td><%#= client.client_unit_price.unit_price_id %></td>-->
<!--        <td><%#= client.publishing_fee.value %></td>-->
<!--        <td><%#= client.client_unit_price.id %></td>-->
        <% if client.client_publishing_setting.client.blank? %>
        <% else %>
          <td><%= link_to 'Show', client_path(client.client_publishing_setting.client.id) %></td>
<!--          <td><%#= link_to 'Edit', edit_client_path(client) %></td>-->
<!--          <td><%#= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
        <% end %>

          </tr>
    <% end %>
  </tbody>
</table>
<!--  <tbody>-->
    <%# @clients.each do |client| %>
<!--      <tr>-->
<!--        <td><%#= client.id %></td>-->
<!--        <td><%#= client.client_id %></td>-->
<!--        <td><%#= client.comment %></td>-->
<!--        <td><%#= client.client.name %></td>-->
<!--        <td><%#= link_to 'Show', client %></td>-->
<!--        <td><%#= link_to 'Edit', edit_client_path(client) %></td>-->
<!--        <td><%#= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--      </tr>-->
    <%# end %>
<!--  </tbody>-->
<!--</table>-->

<br>

<%= link_to 'New Client', new_client_path %>


<%#= javascript_pack_tag 'ClientIndexPage_vue' %>
<%#= stylesheet_pack_tag 'ClientIndexPage_vue' %>

myblog/app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

myblog/app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'basic_info', client: @client %>
<%= render 'publishing_setting', publishing_setting: @publishing_setting %>

<%#= render 'publishing_term', publishing_term: @publishing_term %>