myblog/config/routes.rb
Rails.application.routes.draw do
  resources :publishing_terms
  resources :unit_prices
  resources :contact_histories
  resources :notification2s
  resources :notifications
  resources :publishing_fees
  resources :client_unit_prices
  resources :client_publishing_settings
  devise_for :users
  get 'welcome/index'
  resources :categories
  resources :shops
  resources :diaries
  resources :articles
  resources :clients


  # namespace :api, {format: 'json'} do
  #   namespace :v1 do
  #     resources :articles, only: [:index, :show, :create]
  #     resources :clients, only: [:index, :show, :create]
  #     resources :product, only: [:index, :show]
  #   end
  # end

  root "welcome#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

myblog/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
end

myblog/app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    if params[:name_key]
      @articles = Article.where('name LIKE ?', "%#{params[:name_key]}%")
    else
      # @articles = Article.all
      @articles = Article.includes(:user)
    end
    render json: @articles
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    # @article = Article.find(params[:id])
    render json: @article
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    if user_signed_in?
      @article.user_id = current_user.id
    end

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    if @article.user_id == current_user.id
      respond_to do |format|
        if @article.update(article_params)
          format.html { redirect_to @article, notice: 'Article was successfully updated.' }
          format.json { render :show, status: :ok, location: @article }
        else
          format.html { render :edit }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to @article, notice: "You don't have permission."
    end



  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    if @article.user_id == current_user.id
      @article.destroy
      msg = "Article was successfully destroyed."
    else
      msg = "You don't have permission."
    end
    respond_to do |format|
      format.html { redirect_to articles_url, notice: msg }
      format.json { head :no_content }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:content, :name, :feeling)
    end
end

myblog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    if params[:name_key]
      @articles = Article.where('name LIKE ?', "%#{params[:name_key]}%")
    else
      @articles = Article.all
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    if user_signed_in?
      @article.user_id = current_user.id
    end

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    if @article.user_id == current_user.id
      respond_to do |format|
        if @article.update(article_params)
          format.html { redirect_to @article, notice: 'Article was successfully updated.' }
          format.json { render :show, status: :ok, location: @article }
        else
          format.html { render :edit }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to @article, notice: "You don't have permission."
    end



  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    if @article.user_id == current_user.id
      @article.destroy
      msg = "Article was successfully destroyed."
    else
      msg = "You don't have permission."
    end
    respond_to do |format|
      format.html { redirect_to articles_url, notice: msg }
      format.json { head :no_content }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:content, :name, :feeling)
    end
end

myblog/app/helpers/articles_helper.rb
module ArticlesHelper
end

myblog/app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

<!--  <div class="field">-->
    <%#= form.label :name %>
    <%#= form.text_field :name %>
<!--  </div>-->

  <div class="field">
    <%= form.label :feeling %>
    <%= form.text_field :feeling %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.select :category_id, Shop.all.map{|o| [o.name, o.id]} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

myblog/app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

myblog/app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<%= form_tag('/articles', method: 'get') do %>
  <%= label_tag(:name_key, 'Search name:') %>
  <%= text_field_tag(:name_key) %>
  <%= submit_tag('Search') %> <%= link_to 'Clear', articles_path %>
<% end %>

<br>
<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Name</th>
      <th>User name</th>
      <th>User email</th>
      <th>Feeling</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.content %></td>
        <td><%= article.name %></td>
        <td><%= article.user.name %></td>
        <td><%= article.user.email %></td>
        <td><%= article.feeling %></td>
        <td><%= link_to 'Show', article %></td>
        <% if user_signed_in? && article.user_id == current_user.id %>
          <td><%= link_to 'Edit', edit_article_path(article) %></td>
          <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>
<%= link_to 'Shops', shops_path %>

<%= javascript_pack_tag 'hello_vue' %>
<%= stylesheet_pack_tag 'hello_vue' %>

<%#= javascript_pack_tag 'hello_vue2' %>
<%#= stylesheet_pack_tag 'hello_vue2' %>

<!--<div id="app">-->
<!--  <p>{{ message }}</p>-->
<!--</div>-->

<!--<script src="https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js"></script>-->
<!--<script src="../../javascript/packs/hello.js"></script>-->
<!--<script src="js/hello.js"></script>-->

myblog/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

myblog/app/views/articles/show.html.erb
<!--<p id="notice"><%#= notice %></p>-->

<!--<p>-->
<!--  <strong>Name:</strong>-->
  <%#= @article.user.name %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Content:</strong>-->
  <%#= @article.content %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Name:</strong>-->
  <%#= @article.name %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Feeling:</strong>-->
  <%#= @article.feeling %>
<!--</p>-->



<%= javascript_pack_tag 'ArticleDetailPage_vue' %>
<%= stylesheet_pack_tag 'ArticleDetailPage_vue' %>

<% if user_signed_in? && article.user_id == current_user.id %>
  <%= link_to 'Edit', edit_article_path(@article) %> |
<% end %>
<%= link_to 'Back', articles_path %>